# Generated by Django 5.0.6 on 2024-06-06 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('correo', models.CharField(max_length=255)),
                ('fechaNacimiento', models.DateField(default='01/01/2000')),
                ('pais', models.CharField(max_length=20)),
                ('genero', models.CharField(max_length=1)),
                ('creadoEn', models.DateTimeField(auto_now_add=True)),
                ('actualizadoEn', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
