# Generated by Django 5.0.6 on 2024-06-06 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='genero',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('O', 'Otro')], max_length=1),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='pais',
            field=models.CharField(choices=[('CL', 'Chile'), ('AR', 'Argentina'), ('BR', 'Brasil')], default='Chile', max_length=20),
        ),
    ]
