# Generated by Django 5.0.6 on 2024-06-14 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_alter_empleado_genero_alter_empleado_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='apellido',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='correo',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fechaNacimiento',
            field=models.DateField(default='01/01/2000', verbose_name='Fecha de Nacimiento'),
        ),
    ]
